### ISSUE TITLE
Optional or Default Hydration

### ISSUE THREAD

**Issue by issackelly** [automerge/autosurgeon#32]
I would like to support fowards-only migrations in an easier path.

I have a struct

```
#[derive(Reconcile, Hydrate)]
pub struct Person {
  #[key]
  pub id: Uuid,
  pub name: String,
 }
 ```
 
 Which i have been using in my document.
 
 I would like to start tracking emails, but I don't have them for the past.
 
 I would hope that one of these would work, instead of an offline document migration.
 
 ```
#[derive(Reconcile, Hydrate)]
pub struct Person {
  #[key]
  pub id: Uuid,
  pub name: String,
  pub email: Option<String>
 }
```

```
#[derive(Reconcile, Hydrate, Default)]
pub struct Person {
  #[key]
  pub id: Uuid,
  pub name: String,
  pub email: String
 }
```

**Comment by alexjg** [comment]
My feeling is that this shouldn't happen automatically but should instead be driven by some kind of `missing=` attribute, a bit like `serde`. Something like this:

```rust
pub struct Person {
    #[key]
    pub id: Uuid,
    pub name: String,
    #[missing=default]
    pub email: Option<String>,
}
```

I think this is nice for two reasons:

1. It's easier to distinguish between fields which are automatically populated by the `default` and fields in which `None` has some semantic meaning beyond "this field was originally null"
2. It gives us a hook to do more than just populate missing values with `None`. For example, you may want an enum which has a specific field for "pre-migrated" data of some kind.

What do you think?

**Comment by issackelly** [comment]
I agree that's a better idea.

**Comment by teohhanhui** [comment]
Also, what do you think about this syntax?

```rust
pub struct Person {
    #[key]
    pub id: Uuid,
    pub name: String,
    #[missing = Default::default]
    pub email: Option<String>,
}
```

IIUC it's easier to parse this with `syn` out of the box...
