### ISSUE TITLE
Fix trait errors with overriden automerge

### ISSUE THREAD

**Issue by gterzian** [automerge/autosurgeon#36]
Follow-up on https://github.com/automerge/autosurgeon/issues/31 (which I  tried to re-open). 

I am still having the  problem when using my own local checked-out version of Automerge at 0.5.1, and Autosurgeon at 0.8. 

Is there a reason why this would only happen when working with your own checked-out Automerge as a `path` dependency?

For example:

```
error[E0277]: the trait bound `Transaction<'_>: autosurgeon::ReadDoc` is not satisfied
   --> examples/distributed_bakery.rs:476:27
    |
476 |                 reconcile(&mut tx, &bakery).unwrap();
    |                 --------- ^^^^^^^ the trait `autosurgeon::ReadDoc` is not implemented for `Transaction<'_>`
    |                 |
    |                 required by a bound introduced by this call
    |
    = help: the following other types implement trait `autosurgeon::ReadDoc`:
              automerge::autocommit::AutoCommit
              automerge::automerge::Automerge
              automerge::transaction::manual_transaction::Transaction<'a>
    = note: required for `Transaction<'_>` to implement `Doc`
note: required by a bound in `autosurgeon::reconcile`
```

**Comment by gterzian** [comment]
problem goes away when using `[patch.crates-io]` to override the dependency...

**Comment by issackelly** [comment]
Yeah I think it was related to automerge-test depending on a fixed version and manually editing Cargo.toml -- I had the same trouble this week. (saving notes here for next time I run into it, no further action needed)
